# Generated by Django 5.0.3 on 2024-04-09 11:54

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('description', models.CharField(db_index=True, max_length=500, verbose_name='Description')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('place_type', models.CharField(choices=[('Private and Luxury', 'Private and Luxury'), ('Full-day Tours', 'Full-day Tours'), ('Day trips', 'Day trips'), ('Forest', 'Forest'), ('Favourites', 'Favourites')], max_length=50, verbose_name='Place Type')),
                ('googel_map_link', models.CharField(max_length=500, verbose_name='Googel Map Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'db_table': 'placeAround',
            },
        ),
    ]
